version: "3.4"
services:
  database:
    image: postgres:11-alpine
    environment:
       - POSTGRES_DB=skeleton 
       - POSTGRES_USER=skeleton_user
       - POSTGRES_PASSWORD=skeleton_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  
  backend:
    build: .
    ports:
      - "8080:8080"
    image: "gradle:latest"
    links: 
      -  "database"


volumes:
  db-data:
